#!/bin/bash

list_db () {
    echo "Here are the current book entries:"
    scripts/list_db.py
    echo -n "Enter book id: "
}

check_exit () {
    if [[ $? != 0 ]]
    then
        echo "Internal Error: check arguments and/or inputs."
    fi
}

confirm () {
    echo -n "Confirm? (Y/N): "
    read confirm_yn
    if [[ "$confirm_yn" == "Y" ]]
    then
        scripts/$1 $2 2>/dev/null
        check_exit
    else
        echo "Aborting!" 
    fi
}

scripts/create_db.py

while :
do
    echo -e "Available Actions: [l] = List, [n] = New Book, [r] = Remove Book,\n[p] = Progress, [s] = Set Status, [b] = Build, [e] = Exit"
    echo -n "Enter an action: "
    read curr_action
    case "$curr_action" in
        l)
            list_db
            ;;
        n)
            echo -n "Enter book title: "
            read book_title
            echo -n "Enter book author(s): "
            read book_author
            scripts/new_book.py "$book_title" "$book_author" 2>/dev/null
            check_exit
            ;;
        r)
            list_db
            read rm_id
            confirm "rm_book.py" $rm_id
            ;;
        p)
            list_db
            read prog_id
            confirm "prog_book.py" $prog_id
            ;;
        s)
            list_db
            read stat_id
            echo "Status Options: [0] = Ongoing, [1] = Hold, [2] = Concluded"
            echo -n "Enter an Option: "
            read stat_op
            scripts/stat_book.py $stat_id $stat_op 2>/dev/null
            check_exit
            ;;
        b)
            echo "Building..."
            scripts/build_html.py > docs/index.html
            echo "Done!"
            ;;
        e)
            echo "Goodbye."
            exit 0
            ;;
        *)
            echo "Unknown action."
            ;;
    esac
done
